// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjD00zW5kM5eVryTYmqhFmVLHVipMoj9U',
    appId: '1:881124446713:web:5dc6427146a1409ccead28',
    messagingSenderId: '881124446713',
    projectId: 'olie-mvp',
    authDomain: 'olie-mvp.firebaseapp.com',
    storageBucket: 'olie-mvp.appspot.com',
    measurementId: 'G-PLFNLM5NFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFj77DNxwa16_CdLHmGF8a_a8fexi56J4',
    appId: '1:881124446713:android:6354fa4ab5f9cde0cead28',
    messagingSenderId: '881124446713',
    projectId: 'olie-mvp',
    storageBucket: 'olie-mvp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrGGJVG2ezgFoDgu1y-zgTPFvRtP5CLG8',
    appId: '1:881124446713:ios:e8400c5e6b79473acead28',
    messagingSenderId: '881124446713',
    projectId: 'olie-mvp',
    storageBucket: 'olie-mvp.appspot.com',
    iosBundleId: 'com.example.olieMvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrGGJVG2ezgFoDgu1y-zgTPFvRtP5CLG8',
    appId: '1:881124446713:ios:e8400c5e6b79473acead28',
    messagingSenderId: '881124446713',
    projectId: 'olie-mvp',
    storageBucket: 'olie-mvp.appspot.com',
    iosBundleId: 'com.example.olieMvp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjD00zW5kM5eVryTYmqhFmVLHVipMoj9U',
    appId: '1:881124446713:web:76cb8b47d9be2713cead28',
    messagingSenderId: '881124446713',
    projectId: 'olie-mvp',
    authDomain: 'olie-mvp.firebaseapp.com',
    storageBucket: 'olie-mvp.appspot.com',
    measurementId: 'G-7M5V36B38J',
  );
}
